key: 169855612:AAhKi96n8kGDjX9DUdYr2TndhrnOoofCci2
emoticons:
    - (｡・`ω´･)
    - o(*≧▽≦)ツ
    - ≖‿≖✧
    - (´･ω･｀)
    - (╯‵□′)╯︵┻━┻
    - ∑(っ °Д °;)っ
    - (ノ｀Д´)ノ┻━┻
    - (・∀・)
    - (*/ω＼*)
    - (●´∀‘●）
    - ヾ(❀╹◡╹)ﾉ~
    - (◕ω＜)☆
    - ~\(≥▽≤)/~
    - \*罒▽罒\*
    - ´∀`
    - o(*≥▽≤)ツ┏━┓
    - (｡ゝω・｡)ゞ
    - ≧ω≦
    - ≧▽≦
    - ＞ω＜
    - ＞﹏＜
    - ≧﹏≦
    - ≧△≦
    - (・_・)
